/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package to.unified.unifiedto.models.operations;

import to.unified.unifiedto.utils.Utils;

public class RemoveKmsSpaceRequestBuilder {

    private RemoveKmsSpaceRequest request;
    private final SDKMethodInterfaces.MethodCallRemoveKmsSpace sdk;

    public RemoveKmsSpaceRequestBuilder(SDKMethodInterfaces.MethodCallRemoveKmsSpace sdk) {
        this.sdk = sdk;
    }

    public RemoveKmsSpaceRequestBuilder request(RemoveKmsSpaceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RemoveKmsSpaceResponse call() throws Exception {

        return sdk.removeKmsSpace(
            request);
    }
}
