/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package to.unified.unifiedto.models.operations;

import to.unified.unifiedto.utils.Utils;

public class RemoveUnifiedWebhookRequestBuilder {

    private RemoveUnifiedWebhookRequest request;
    private final SDKMethodInterfaces.MethodCallRemoveUnifiedWebhook sdk;

    public RemoveUnifiedWebhookRequestBuilder(SDKMethodInterfaces.MethodCallRemoveUnifiedWebhook sdk) {
        this.sdk = sdk;
    }

    public RemoveUnifiedWebhookRequestBuilder request(RemoveUnifiedWebhookRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RemoveUnifiedWebhookResponse call() throws Exception {

        return sdk.removeUnifiedWebhook(
            request);
    }
}
