/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package to.unified.unifiedto.models.operations;

import to.unified.unifiedto.utils.Utils;

public class UpdateLmsCourseRequestBuilder {

    private UpdateLmsCourseRequest request;
    private final SDKMethodInterfaces.MethodCallUpdateLmsCourse sdk;

    public UpdateLmsCourseRequestBuilder(SDKMethodInterfaces.MethodCallUpdateLmsCourse sdk) {
        this.sdk = sdk;
    }

    public UpdateLmsCourseRequestBuilder request(UpdateLmsCourseRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UpdateLmsCourseResponse call() throws Exception {

        return sdk.updateLmsCourse(
            request);
    }
}
