/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unifiedapi.unifiedto.models.shared.TicketingTicket;
import com.unifiedapi.unifiedto.utils.SpeakeasyMetadata;
import com.unifiedapi.unifiedto.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class CreateTicketingTicketRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private TicketingTicket ticketingTicket;

    /**
     * ID of the connection
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connection_id")
    private String connectionId;

    /**
     * Comma-delimited fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    private Optional<? extends List<String>> fields;

    @JsonCreator
    public CreateTicketingTicketRequest(
            TicketingTicket ticketingTicket,
            String connectionId,
            Optional<? extends List<String>> fields) {
        Utils.checkNotNull(ticketingTicket, "ticketingTicket");
        Utils.checkNotNull(connectionId, "connectionId");
        Utils.checkNotNull(fields, "fields");
        this.ticketingTicket = ticketingTicket;
        this.connectionId = connectionId;
        this.fields = fields;
    }
    
    public CreateTicketingTicketRequest(
            TicketingTicket ticketingTicket,
            String connectionId) {
        this(ticketingTicket, connectionId, Optional.empty());
    }

    @JsonIgnore
    public TicketingTicket ticketingTicket() {
        return ticketingTicket;
    }

    /**
     * ID of the connection
     */
    @JsonIgnore
    public String connectionId() {
        return connectionId;
    }

    /**
     * Comma-delimited fields to return
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> fields() {
        return (Optional<List<String>>) fields;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreateTicketingTicketRequest withTicketingTicket(TicketingTicket ticketingTicket) {
        Utils.checkNotNull(ticketingTicket, "ticketingTicket");
        this.ticketingTicket = ticketingTicket;
        return this;
    }

    /**
     * ID of the connection
     */
    public CreateTicketingTicketRequest withConnectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    /**
     * Comma-delimited fields to return
     */
    public CreateTicketingTicketRequest withFields(List<String> fields) {
        Utils.checkNotNull(fields, "fields");
        this.fields = Optional.ofNullable(fields);
        return this;
    }

    /**
     * Comma-delimited fields to return
     */
    public CreateTicketingTicketRequest withFields(Optional<? extends List<String>> fields) {
        Utils.checkNotNull(fields, "fields");
        this.fields = fields;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateTicketingTicketRequest other = (CreateTicketingTicketRequest) o;
        return 
            Objects.deepEquals(this.ticketingTicket, other.ticketingTicket) &&
            Objects.deepEquals(this.connectionId, other.connectionId) &&
            Objects.deepEquals(this.fields, other.fields);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            ticketingTicket,
            connectionId,
            fields);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateTicketingTicketRequest.class,
                "ticketingTicket", ticketingTicket,
                "connectionId", connectionId,
                "fields", fields);
    }
    
    public final static class Builder {
 
        private TicketingTicket ticketingTicket;
 
        private String connectionId;
 
        private Optional<? extends List<String>> fields = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder ticketingTicket(TicketingTicket ticketingTicket) {
            Utils.checkNotNull(ticketingTicket, "ticketingTicket");
            this.ticketingTicket = ticketingTicket;
            return this;
        }

        /**
         * ID of the connection
         */
        public Builder connectionId(String connectionId) {
            Utils.checkNotNull(connectionId, "connectionId");
            this.connectionId = connectionId;
            return this;
        }

        /**
         * Comma-delimited fields to return
         */
        public Builder fields(List<String> fields) {
            Utils.checkNotNull(fields, "fields");
            this.fields = Optional.ofNullable(fields);
            return this;
        }

        /**
         * Comma-delimited fields to return
         */
        public Builder fields(Optional<? extends List<String>> fields) {
            Utils.checkNotNull(fields, "fields");
            this.fields = fields;
            return this;
        }
        
        public CreateTicketingTicketRequest build() {
            return new CreateTicketingTicketRequest(
                ticketingTicket,
                connectionId,
                fields);
        }
    }
}

