/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.operations;

import com.unifiedapi.unifiedto.utils.Utils;

public class GetPaymentLinkRequestBuilder {

    private GetPaymentLinkRequest request;
    private final SDKMethodInterfaces.MethodCallGetPaymentLink sdk;

    public GetPaymentLinkRequestBuilder(SDKMethodInterfaces.MethodCallGetPaymentLink sdk) {
        this.sdk = sdk;
    }

    public GetPaymentLinkRequestBuilder request(com.unifiedapi.unifiedto.models.operations.GetPaymentLinkRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetPaymentLinkResponse call() throws Exception {

        return sdk.getPaymentLink(
            request);
    }
}
