/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.operations;

import com.unifiedapi.unifiedto.utils.Utils;

public class RemoveLmsClassRequestBuilder {

    private RemoveLmsClassRequest request;
    private final SDKMethodInterfaces.MethodCallRemoveLmsClass sdk;

    public RemoveLmsClassRequestBuilder(SDKMethodInterfaces.MethodCallRemoveLmsClass sdk) {
        this.sdk = sdk;
    }

    public RemoveLmsClassRequestBuilder request(RemoveLmsClassRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RemoveLmsClassResponse call() throws Exception {

        return sdk.removeLmsClass(
            request);
    }
}
