/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.operations;

import com.unifiedapi.unifiedto.utils.Utils;

public class UpdateKmsSpaceRequestBuilder {

    private UpdateKmsSpaceRequest request;
    private final SDKMethodInterfaces.MethodCallUpdateKmsSpace sdk;

    public UpdateKmsSpaceRequestBuilder(SDKMethodInterfaces.MethodCallUpdateKmsSpace sdk) {
        this.sdk = sdk;
    }

    public UpdateKmsSpaceRequestBuilder request(UpdateKmsSpaceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UpdateKmsSpaceResponse call() throws Exception {

        return sdk.updateKmsSpace(
            request);
    }
}
