/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.models.operations.ListRepoOrganizationsRequest;
import to.unified.unified_java_sdk.operations.ListRepoOrganizations;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class ListRepoOrganizationsRequestBuilder {

    private ListRepoOrganizationsRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListRepoOrganizationsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListRepoOrganizationsRequestBuilder request(ListRepoOrganizationsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<ListRepoOrganizationsResponse> call() throws Exception {
        
        AsyncRequestOperation<ListRepoOrganizationsRequest, ListRepoOrganizationsResponse> operation
              = new ListRepoOrganizations.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
