/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.AccountingProfitloss;
import to.unified.unified_java_sdk.utils.AsyncResponse;
import to.unified.unified_java_sdk.utils.Blob;
import to.unified.unified_java_sdk.utils.Utils;


public class ListAccountingProfitlossesResponse implements AsyncResponse {
    /**
     * Successful
     */
    private List<AccountingProfitloss> accountingProfitlosses;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    @JsonCreator
    public ListAccountingProfitlossesResponse(
            @Nullable List<AccountingProfitloss> accountingProfitlosses,
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this.accountingProfitlosses = accountingProfitlosses;
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
    }
    
    public ListAccountingProfitlossesResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this(null, contentType, statusCode,
            rawResponse);
    }

    /**
     * Successful
     */
    public Optional<List<AccountingProfitloss>> accountingProfitlosses() {
        return Optional.ofNullable(this.accountingProfitlosses);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Successful
     */
    public ListAccountingProfitlossesResponse withAccountingProfitlosses(@Nullable List<AccountingProfitloss> accountingProfitlosses) {
        this.accountingProfitlosses = accountingProfitlosses;
        return this;
    }


    /**
     * HTTP response content type for this operation
     */
    public ListAccountingProfitlossesResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public ListAccountingProfitlossesResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListAccountingProfitlossesResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListAccountingProfitlossesResponse other = (ListAccountingProfitlossesResponse) o;
        return 
            Utils.enhancedDeepEquals(this.accountingProfitlosses, other.accountingProfitlosses) &&
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountingProfitlosses, contentType, statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListAccountingProfitlossesResponse.class,
                "accountingProfitlosses", accountingProfitlosses,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<AccountingProfitloss> accountingProfitlosses;

        private String contentType;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Successful
         */
        public Builder accountingProfitlosses(@Nullable List<AccountingProfitloss> accountingProfitlosses) {
            this.accountingProfitlosses = accountingProfitlosses;
            return this;
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        public ListAccountingProfitlossesResponse build() {
            return new ListAccountingProfitlossesResponse(
                accountingProfitlosses, contentType, statusCode,
                rawResponse);
        }

    }
}
