/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.models.operations.PatchPaymentPaymentRequest;
import to.unified.unified_java_sdk.operations.PatchPaymentPayment;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class PatchPaymentPaymentRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private PatchPaymentPaymentRequest request;

    public PatchPaymentPaymentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PatchPaymentPaymentRequestBuilder request(@Nonnull PatchPaymentPaymentRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private PatchPaymentPaymentRequest _buildRequest() {
        return this.request;
    }
    
    public PatchPaymentPaymentRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<PatchPaymentPaymentResponse> call() {
        AsyncRequestOperation<PatchPaymentPaymentRequest, PatchPaymentPaymentResponse> operation
              = new PatchPaymentPayment.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
