/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.models.operations.PatchRepoBranchRequest;
import to.unified.unified_java_sdk.operations.PatchRepoBranch;
import to.unified.unified_java_sdk.utils.Utils;

public class PatchRepoBranchRequestBuilder {

    private PatchRepoBranchRequest request;
    private final SDKConfiguration sdkConfiguration;

    public PatchRepoBranchRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PatchRepoBranchRequestBuilder request(PatchRepoBranchRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<PatchRepoBranchResponse> call() throws Exception {
        
        AsyncRequestOperation<PatchRepoBranchRequest, PatchRepoBranchResponse> operation
              = new PatchRepoBranch.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
