/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.models.operations.RemoveTicketingCustomer2Request;
import to.unified.unified_java_sdk.operations.RemoveTicketingCustomer2;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class RemoveTicketingCustomer2RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private RemoveTicketingCustomer2Request request;

    public RemoveTicketingCustomer2RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RemoveTicketingCustomer2RequestBuilder request(@Nonnull RemoveTicketingCustomer2Request request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private RemoveTicketingCustomer2Request _buildRequest() {
        return this.request;
    }
    
    public RemoveTicketingCustomer2RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<RemoveTicketingCustomer2Response> call() {
        AsyncRequestOperation<RemoveTicketingCustomer2Request, RemoveTicketingCustomer2Response> operation
              = new RemoveTicketingCustomer2.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
