/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.models.operations.UpdateCrmPipelineRequest;
import to.unified.unified_java_sdk.operations.UpdateCrmPipeline;
import to.unified.unified_java_sdk.utils.Utils;

public class UpdateCrmPipelineRequestBuilder {

    private UpdateCrmPipelineRequest request;
    private final SDKConfiguration sdkConfiguration;

    public UpdateCrmPipelineRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public UpdateCrmPipelineRequestBuilder request(UpdateCrmPipelineRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<UpdateCrmPipelineResponse> call() throws Exception {
        
        AsyncRequestOperation<UpdateCrmPipelineRequest, UpdateCrmPipelineResponse> operation
              = new UpdateCrmPipeline.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
