/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.unifiedapi.unifiedto.models.shared;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.unifiedapi.unifiedto.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class ScimGroup {

    @JsonProperty("displayName")
    private String displayName;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("externalId")
    private Optional<String> externalId;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("groupType")
    private Optional<String> groupType;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    /**
     * An array of members
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("members")
    private Optional<? extends List<ScimGroupMember>> members;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    private Optional<? extends PropertyScimGroupMeta> meta;

    /**
     * Array of schema URIs
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schemas")
    private Optional<? extends List<PropertyScimGroupSchemas>> schemas;

    @JsonCreator
    public ScimGroup(
            @JsonProperty("displayName") String displayName,
            @JsonProperty("externalId") Optional<String> externalId,
            @JsonProperty("groupType") Optional<String> groupType,
            @JsonProperty("id") Optional<String> id,
            @JsonProperty("members") Optional<? extends List<ScimGroupMember>> members,
            @JsonProperty("meta") Optional<? extends PropertyScimGroupMeta> meta,
            @JsonProperty("schemas") Optional<? extends List<PropertyScimGroupSchemas>> schemas) {
        Utils.checkNotNull(displayName, "displayName");
        Utils.checkNotNull(externalId, "externalId");
        Utils.checkNotNull(groupType, "groupType");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(members, "members");
        Utils.checkNotNull(meta, "meta");
        Utils.checkNotNull(schemas, "schemas");
        this.displayName = displayName;
        this.externalId = externalId;
        this.groupType = groupType;
        this.id = id;
        this.members = members;
        this.meta = meta;
        this.schemas = schemas;
    }
    
    public ScimGroup(
            String displayName) {
        this(displayName, Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    @JsonIgnore
    public Optional<String> externalId() {
        return externalId;
    }

    @JsonIgnore
    public Optional<String> groupType() {
        return groupType;
    }

    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    /**
     * An array of members
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<ScimGroupMember>> members() {
        return (Optional<List<ScimGroupMember>>) members;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PropertyScimGroupMeta> meta() {
        return (Optional<PropertyScimGroupMeta>) meta;
    }

    /**
     * Array of schema URIs
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<PropertyScimGroupSchemas>> schemas() {
        return (Optional<List<PropertyScimGroupSchemas>>) schemas;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ScimGroup withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    public ScimGroup withExternalId(String externalId) {
        Utils.checkNotNull(externalId, "externalId");
        this.externalId = Optional.ofNullable(externalId);
        return this;
    }

    public ScimGroup withExternalId(Optional<String> externalId) {
        Utils.checkNotNull(externalId, "externalId");
        this.externalId = externalId;
        return this;
    }

    public ScimGroup withGroupType(String groupType) {
        Utils.checkNotNull(groupType, "groupType");
        this.groupType = Optional.ofNullable(groupType);
        return this;
    }

    public ScimGroup withGroupType(Optional<String> groupType) {
        Utils.checkNotNull(groupType, "groupType");
        this.groupType = groupType;
        return this;
    }

    public ScimGroup withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    public ScimGroup withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * An array of members
     */
    public ScimGroup withMembers(List<ScimGroupMember> members) {
        Utils.checkNotNull(members, "members");
        this.members = Optional.ofNullable(members);
        return this;
    }

    /**
     * An array of members
     */
    public ScimGroup withMembers(Optional<? extends List<ScimGroupMember>> members) {
        Utils.checkNotNull(members, "members");
        this.members = members;
        return this;
    }

    public ScimGroup withMeta(PropertyScimGroupMeta meta) {
        Utils.checkNotNull(meta, "meta");
        this.meta = Optional.ofNullable(meta);
        return this;
    }

    public ScimGroup withMeta(Optional<? extends PropertyScimGroupMeta> meta) {
        Utils.checkNotNull(meta, "meta");
        this.meta = meta;
        return this;
    }

    /**
     * Array of schema URIs
     */
    public ScimGroup withSchemas(List<PropertyScimGroupSchemas> schemas) {
        Utils.checkNotNull(schemas, "schemas");
        this.schemas = Optional.ofNullable(schemas);
        return this;
    }

    /**
     * Array of schema URIs
     */
    public ScimGroup withSchemas(Optional<? extends List<PropertyScimGroupSchemas>> schemas) {
        Utils.checkNotNull(schemas, "schemas");
        this.schemas = schemas;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ScimGroup other = (ScimGroup) o;
        return 
            Objects.deepEquals(this.displayName, other.displayName) &&
            Objects.deepEquals(this.externalId, other.externalId) &&
            Objects.deepEquals(this.groupType, other.groupType) &&
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.members, other.members) &&
            Objects.deepEquals(this.meta, other.meta) &&
            Objects.deepEquals(this.schemas, other.schemas);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            displayName,
            externalId,
            groupType,
            id,
            members,
            meta,
            schemas);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ScimGroup.class,
                "displayName", displayName,
                "externalId", externalId,
                "groupType", groupType,
                "id", id,
                "members", members,
                "meta", meta,
                "schemas", schemas);
    }
    
    public final static class Builder {
 
        private String displayName;
 
        private Optional<String> externalId = Optional.empty();
 
        private Optional<String> groupType = Optional.empty();
 
        private Optional<String> id = Optional.empty();
 
        private Optional<? extends List<ScimGroupMember>> members = Optional.empty();
 
        private Optional<? extends PropertyScimGroupMeta> meta = Optional.empty();
 
        private Optional<? extends List<PropertyScimGroupSchemas>> schemas = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }

        public Builder externalId(String externalId) {
            Utils.checkNotNull(externalId, "externalId");
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        public Builder externalId(Optional<String> externalId) {
            Utils.checkNotNull(externalId, "externalId");
            this.externalId = externalId;
            return this;
        }

        public Builder groupType(String groupType) {
            Utils.checkNotNull(groupType, "groupType");
            this.groupType = Optional.ofNullable(groupType);
            return this;
        }

        public Builder groupType(Optional<String> groupType) {
            Utils.checkNotNull(groupType, "groupType");
            this.groupType = groupType;
            return this;
        }

        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * An array of members
         */
        public Builder members(List<ScimGroupMember> members) {
            Utils.checkNotNull(members, "members");
            this.members = Optional.ofNullable(members);
            return this;
        }

        /**
         * An array of members
         */
        public Builder members(Optional<? extends List<ScimGroupMember>> members) {
            Utils.checkNotNull(members, "members");
            this.members = members;
            return this;
        }

        public Builder meta(PropertyScimGroupMeta meta) {
            Utils.checkNotNull(meta, "meta");
            this.meta = Optional.ofNullable(meta);
            return this;
        }

        public Builder meta(Optional<? extends PropertyScimGroupMeta> meta) {
            Utils.checkNotNull(meta, "meta");
            this.meta = meta;
            return this;
        }

        /**
         * Array of schema URIs
         */
        public Builder schemas(List<PropertyScimGroupSchemas> schemas) {
            Utils.checkNotNull(schemas, "schemas");
            this.schemas = Optional.ofNullable(schemas);
            return this;
        }

        /**
         * Array of schema URIs
         */
        public Builder schemas(Optional<? extends List<PropertyScimGroupSchemas>> schemas) {
            Utils.checkNotNull(schemas, "schemas");
            this.schemas = schemas;
            return this;
        }
        
        public ScimGroup build() {
            return new ScimGroup(
                displayName,
                externalId,
                groupType,
                id,
                members,
                meta,
                schemas);
        }
    }
}

