/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.models.operations.ListCalendarBusies2Request;
import to.unified.unified_java_sdk.models.operations.ListCalendarBusies2RequestBuilder;
import to.unified.unified_java_sdk.models.operations.ListCalendarBusies2Response;
import to.unified.unified_java_sdk.operations.ListCalendarBusies2;
import to.unified.unified_java_sdk.utils.Headers;


public class Busy {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncBusy asyncSDK;

    Busy(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncBusy(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncBusy async() {
        return asyncSDK;
    }

    /**
     * List all busies
     * 
     * @return The call builder
     */
    public ListCalendarBusies2RequestBuilder listCalendarBusies2() {
        return new ListCalendarBusies2RequestBuilder(sdkConfiguration);
    }

    /**
     * List all busies
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListCalendarBusies2Response listCalendarBusies2(@Nonnull ListCalendarBusies2Request request) {
        RequestOperation<ListCalendarBusies2Request, ListCalendarBusies2Response> operation
              = new ListCalendarBusies2.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
