/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.models.operations.CreateDatastoreTableRequest;
import to.unified.unified_java_sdk.models.operations.CreateDatastoreTableRequestBuilder;
import to.unified.unified_java_sdk.models.operations.CreateDatastoreTableResponse;
import to.unified.unified_java_sdk.models.operations.GetDatastoreTableRequest;
import to.unified.unified_java_sdk.models.operations.GetDatastoreTableRequestBuilder;
import to.unified.unified_java_sdk.models.operations.GetDatastoreTableResponse;
import to.unified.unified_java_sdk.models.operations.ListDatastoreTablesRequest;
import to.unified.unified_java_sdk.models.operations.ListDatastoreTablesRequestBuilder;
import to.unified.unified_java_sdk.models.operations.ListDatastoreTablesResponse;
import to.unified.unified_java_sdk.models.operations.PatchDatastoreTableRequest;
import to.unified.unified_java_sdk.models.operations.PatchDatastoreTableRequestBuilder;
import to.unified.unified_java_sdk.models.operations.PatchDatastoreTableResponse;
import to.unified.unified_java_sdk.models.operations.RemoveDatastoreTableRequest;
import to.unified.unified_java_sdk.models.operations.RemoveDatastoreTableRequestBuilder;
import to.unified.unified_java_sdk.models.operations.RemoveDatastoreTableResponse;
import to.unified.unified_java_sdk.models.operations.UpdateDatastoreTableRequest;
import to.unified.unified_java_sdk.models.operations.UpdateDatastoreTableRequestBuilder;
import to.unified.unified_java_sdk.models.operations.UpdateDatastoreTableResponse;
import to.unified.unified_java_sdk.operations.CreateDatastoreTable;
import to.unified.unified_java_sdk.operations.GetDatastoreTable;
import to.unified.unified_java_sdk.operations.ListDatastoreTables;
import to.unified.unified_java_sdk.operations.PatchDatastoreTable;
import to.unified.unified_java_sdk.operations.RemoveDatastoreTable;
import to.unified.unified_java_sdk.operations.UpdateDatastoreTable;
import to.unified.unified_java_sdk.utils.Headers;


public class Table {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTable asyncSDK;

    Table(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTable(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTable async() {
        return asyncSDK;
    }

    /**
     * Create a table
     * 
     * @return The call builder
     */
    public CreateDatastoreTableRequestBuilder createDatastoreTable() {
        return new CreateDatastoreTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a table
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateDatastoreTableResponse createDatastoreTable(@Nonnull CreateDatastoreTableRequest request) {
        RequestOperation<CreateDatastoreTableRequest, CreateDatastoreTableResponse> operation
              = new CreateDatastoreTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a table
     * 
     * @return The call builder
     */
    public GetDatastoreTableRequestBuilder getDatastoreTable() {
        return new GetDatastoreTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a table
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDatastoreTableResponse getDatastoreTable(@Nonnull GetDatastoreTableRequest request) {
        RequestOperation<GetDatastoreTableRequest, GetDatastoreTableResponse> operation
              = new GetDatastoreTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List all tables
     * 
     * @return The call builder
     */
    public ListDatastoreTablesRequestBuilder listDatastoreTables() {
        return new ListDatastoreTablesRequestBuilder(sdkConfiguration);
    }

    /**
     * List all tables
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListDatastoreTablesResponse listDatastoreTables(@Nonnull ListDatastoreTablesRequest request) {
        RequestOperation<ListDatastoreTablesRequest, ListDatastoreTablesResponse> operation
              = new ListDatastoreTables.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a table
     * 
     * @return The call builder
     */
    public PatchDatastoreTableRequestBuilder patchDatastoreTable() {
        return new PatchDatastoreTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a table
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PatchDatastoreTableResponse patchDatastoreTable(@Nonnull PatchDatastoreTableRequest request) {
        RequestOperation<PatchDatastoreTableRequest, PatchDatastoreTableResponse> operation
              = new PatchDatastoreTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove a table
     * 
     * @return The call builder
     */
    public RemoveDatastoreTableRequestBuilder removeDatastoreTable() {
        return new RemoveDatastoreTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a table
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RemoveDatastoreTableResponse removeDatastoreTable(@Nonnull RemoveDatastoreTableRequest request) {
        RequestOperation<RemoveDatastoreTableRequest, RemoveDatastoreTableResponse> operation
              = new RemoveDatastoreTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a table
     * 
     * @return The call builder
     */
    public UpdateDatastoreTableRequestBuilder updateDatastoreTable() {
        return new UpdateDatastoreTableRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a table
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateDatastoreTableResponse updateDatastoreTable(@Nonnull UpdateDatastoreTableRequest request) {
        RequestOperation<UpdateDatastoreTableRequest, UpdateDatastoreTableResponse> operation
              = new UpdateDatastoreTable.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
