/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AtsTelephoneType {
    WORK("WORK"),
    HOME("HOME"),
    OTHER("OTHER"),
    FAX("FAX"),
    MOBILE("MOBILE");

    @JsonValue
    public final String value;

    private AtsTelephoneType(String value) {
        this.value = value;
    }
}
