/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.unifiedapi.unifiedto.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum HrisEmployeeGender {
    MALE("MALE"),
    FEMALE("FEMALE"),
    INTERSEX("INTERSEX"),
    TRANS("TRANS"),
    NON_BINARY("NON_BINARY");

    @JsonValue
    public final String value;

    private HrisEmployeeGender(String value) {
        this.value = value;
    }
}
