/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class BudgetAllocationType {

    public static final BudgetAllocationType UNSPECIFIED = new BudgetAllocationType("UNSPECIFIED");
    public static final BudgetAllocationType AUTOMATIC = new BudgetAllocationType("AUTOMATIC");
    public static final BudgetAllocationType FIXED = new BudgetAllocationType("FIXED");
    public static final BudgetAllocationType UNLIMITED = new BudgetAllocationType("UNLIMITED");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, BudgetAllocationType> values = createValuesMap();
    private static final Map<String, BudgetAllocationTypeEnum> enums = createEnumsMap();

    private final String value;

    private BudgetAllocationType(String value) {
        this.value = value;
    }

    /**
     * Returns a BudgetAllocationType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as BudgetAllocationType
     */ 
    @JsonCreator
    public static BudgetAllocationType of(String value) {
        synchronized (BudgetAllocationType.class) {
            return values.computeIfAbsent(value, v -> new BudgetAllocationType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<BudgetAllocationTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BudgetAllocationType other = (BudgetAllocationType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "BudgetAllocationType [value=" + value + "]";
    }

    // return an array just like an enum
    public static BudgetAllocationType[] values() {
        synchronized (BudgetAllocationType.class) {
            return values.values().toArray(new BudgetAllocationType[] {});
        }
    }

    private static final Map<String, BudgetAllocationType> createValuesMap() {
        Map<String, BudgetAllocationType> map = new LinkedHashMap<>();
        map.put("UNSPECIFIED", UNSPECIFIED);
        map.put("AUTOMATIC", AUTOMATIC);
        map.put("FIXED", FIXED);
        map.put("UNLIMITED", UNLIMITED);
        return map;
    }

    private static final Map<String, BudgetAllocationTypeEnum> createEnumsMap() {
        Map<String, BudgetAllocationTypeEnum> map = new HashMap<>();
        map.put("UNSPECIFIED", BudgetAllocationTypeEnum.UNSPECIFIED);
        map.put("AUTOMATIC", BudgetAllocationTypeEnum.AUTOMATIC);
        map.put("FIXED", BudgetAllocationTypeEnum.FIXED);
        map.put("UNLIMITED", BudgetAllocationTypeEnum.UNLIMITED);
        return map;
    }
    
    
    public enum BudgetAllocationTypeEnum {

        UNSPECIFIED("UNSPECIFIED"),
        AUTOMATIC("AUTOMATIC"),
        FIXED("FIXED"),
        UNLIMITED("UNLIMITED"),;

        private final String value;

        private BudgetAllocationTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

