/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class CalendarWebinar {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("calendar_id")
    private String calendarId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("capacity")
    private Double capacity;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("conference")
    private List<CalendarConference> conference;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    private OffsetDateTime createdAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end_at")
    private OffsetDateTime endAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_polls")
    private Boolean hasPolls;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_qa")
    private Boolean hasQa;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_recording")
    private Boolean hasRecording;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_auto_approve")
    private Boolean isAutoApprove;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_enabled")
    private Boolean isEnabled;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_webcast")
    private Boolean isWebcast;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("join_url")
    private String joinUrl;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notes")
    private String notes;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("organizer")
    private PropertyCalendarWebinarOrganizer organizer;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("panelist_password")
    private String panelistPassword;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("panelists")
    private List<CalendarWebinarPanelist> panelists;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("raw")
    private Map<String, Object> raw;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recurrence")
    private List<CalendarEventRecurrence> recurrence;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("registrant_password")
    private String registrantPassword;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("registrants")
    private List<CalendarWebinarRegistrant> registrants;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_address")
    private Boolean requireAddress;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_company")
    private Boolean requireCompany;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_email")
    private Boolean requireEmail;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_first_name")
    private Boolean requireFirstName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_job_title")
    private Boolean requireJobTitle;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_last_name")
    private Boolean requireLastName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("require_phone")
    private Boolean requirePhone;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("start_at")
    private OffsetDateTime startAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private CalendarWebinarStatus status;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subject")
    private String subject;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timezone")
    private String timezone;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated_at")
    private OffsetDateTime updatedAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("web_url")
    private String webUrl;

    @JsonCreator
    public CalendarWebinar(
            @JsonProperty("calendar_id") @Nullable String calendarId,
            @JsonProperty("capacity") @Nullable Double capacity,
            @JsonProperty("conference") @Nullable List<CalendarConference> conference,
            @JsonProperty("created_at") @Nullable OffsetDateTime createdAt,
            @JsonProperty("end_at") @Nullable OffsetDateTime endAt,
            @JsonProperty("has_polls") @Nullable Boolean hasPolls,
            @JsonProperty("has_qa") @Nullable Boolean hasQa,
            @JsonProperty("has_recording") @Nullable Boolean hasRecording,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("is_auto_approve") @Nullable Boolean isAutoApprove,
            @JsonProperty("is_enabled") @Nullable Boolean isEnabled,
            @JsonProperty("is_webcast") @Nullable Boolean isWebcast,
            @JsonProperty("join_url") @Nullable String joinUrl,
            @JsonProperty("notes") @Nullable String notes,
            @JsonProperty("organizer") @Nullable PropertyCalendarWebinarOrganizer organizer,
            @JsonProperty("panelist_password") @Nullable String panelistPassword,
            @JsonProperty("panelists") @Nullable List<CalendarWebinarPanelist> panelists,
            @JsonProperty("raw") @Nullable Map<String, Object> raw,
            @JsonProperty("recurrence") @Nullable List<CalendarEventRecurrence> recurrence,
            @JsonProperty("registrant_password") @Nullable String registrantPassword,
            @JsonProperty("registrants") @Nullable List<CalendarWebinarRegistrant> registrants,
            @JsonProperty("require_address") @Nullable Boolean requireAddress,
            @JsonProperty("require_company") @Nullable Boolean requireCompany,
            @JsonProperty("require_email") @Nullable Boolean requireEmail,
            @JsonProperty("require_first_name") @Nullable Boolean requireFirstName,
            @JsonProperty("require_job_title") @Nullable Boolean requireJobTitle,
            @JsonProperty("require_last_name") @Nullable Boolean requireLastName,
            @JsonProperty("require_phone") @Nullable Boolean requirePhone,
            @JsonProperty("start_at") @Nullable OffsetDateTime startAt,
            @JsonProperty("status") @Nullable CalendarWebinarStatus status,
            @JsonProperty("subject") @Nullable String subject,
            @JsonProperty("timezone") @Nullable String timezone,
            @JsonProperty("updated_at") @Nullable OffsetDateTime updatedAt,
            @JsonProperty("web_url") @Nullable String webUrl) {
        this.calendarId = calendarId;
        this.capacity = capacity;
        this.conference = conference;
        this.createdAt = createdAt;
        this.endAt = endAt;
        this.hasPolls = hasPolls;
        this.hasQa = hasQa;
        this.hasRecording = hasRecording;
        this.id = id;
        this.isAutoApprove = isAutoApprove;
        this.isEnabled = isEnabled;
        this.isWebcast = isWebcast;
        this.joinUrl = joinUrl;
        this.notes = notes;
        this.organizer = organizer;
        this.panelistPassword = panelistPassword;
        this.panelists = panelists;
        this.raw = raw;
        this.recurrence = recurrence;
        this.registrantPassword = registrantPassword;
        this.registrants = registrants;
        this.requireAddress = requireAddress;
        this.requireCompany = requireCompany;
        this.requireEmail = requireEmail;
        this.requireFirstName = requireFirstName;
        this.requireJobTitle = requireJobTitle;
        this.requireLastName = requireLastName;
        this.requirePhone = requirePhone;
        this.startAt = startAt;
        this.status = status;
        this.subject = subject;
        this.timezone = timezone;
        this.updatedAt = updatedAt;
        this.webUrl = webUrl;
    }
    
    public CalendarWebinar() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null);
    }

    public Optional<String> calendarId() {
        return Optional.ofNullable(this.calendarId);
    }

    public Optional<Double> capacity() {
        return Optional.ofNullable(this.capacity);
    }

    public Optional<List<CalendarConference>> conference() {
        return Optional.ofNullable(this.conference);
    }

    public Optional<OffsetDateTime> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    public Optional<OffsetDateTime> endAt() {
        return Optional.ofNullable(this.endAt);
    }

    public Optional<Boolean> hasPolls() {
        return Optional.ofNullable(this.hasPolls);
    }

    public Optional<Boolean> hasQa() {
        return Optional.ofNullable(this.hasQa);
    }

    public Optional<Boolean> hasRecording() {
        return Optional.ofNullable(this.hasRecording);
    }

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public Optional<Boolean> isAutoApprove() {
        return Optional.ofNullable(this.isAutoApprove);
    }

    public Optional<Boolean> isEnabled() {
        return Optional.ofNullable(this.isEnabled);
    }

    public Optional<Boolean> isWebcast() {
        return Optional.ofNullable(this.isWebcast);
    }

    public Optional<String> joinUrl() {
        return Optional.ofNullable(this.joinUrl);
    }

    public Optional<String> notes() {
        return Optional.ofNullable(this.notes);
    }

    public Optional<PropertyCalendarWebinarOrganizer> organizer() {
        return Optional.ofNullable(this.organizer);
    }

    public Optional<String> panelistPassword() {
        return Optional.ofNullable(this.panelistPassword);
    }

    public Optional<List<CalendarWebinarPanelist>> panelists() {
        return Optional.ofNullable(this.panelists);
    }

    public Optional<Map<String, Object>> raw() {
        return Optional.ofNullable(this.raw);
    }

    public Optional<List<CalendarEventRecurrence>> recurrence() {
        return Optional.ofNullable(this.recurrence);
    }

    public Optional<String> registrantPassword() {
        return Optional.ofNullable(this.registrantPassword);
    }

    public Optional<List<CalendarWebinarRegistrant>> registrants() {
        return Optional.ofNullable(this.registrants);
    }

    public Optional<Boolean> requireAddress() {
        return Optional.ofNullable(this.requireAddress);
    }

    public Optional<Boolean> requireCompany() {
        return Optional.ofNullable(this.requireCompany);
    }

    public Optional<Boolean> requireEmail() {
        return Optional.ofNullable(this.requireEmail);
    }

    public Optional<Boolean> requireFirstName() {
        return Optional.ofNullable(this.requireFirstName);
    }

    public Optional<Boolean> requireJobTitle() {
        return Optional.ofNullable(this.requireJobTitle);
    }

    public Optional<Boolean> requireLastName() {
        return Optional.ofNullable(this.requireLastName);
    }

    public Optional<Boolean> requirePhone() {
        return Optional.ofNullable(this.requirePhone);
    }

    public Optional<OffsetDateTime> startAt() {
        return Optional.ofNullable(this.startAt);
    }

    public Optional<CalendarWebinarStatus> status() {
        return Optional.ofNullable(this.status);
    }

    public Optional<String> subject() {
        return Optional.ofNullable(this.subject);
    }

    public Optional<String> timezone() {
        return Optional.ofNullable(this.timezone);
    }

    public Optional<OffsetDateTime> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    public Optional<String> webUrl() {
        return Optional.ofNullable(this.webUrl);
    }

    public static Builder builder() {
        return new Builder();
    }


    public CalendarWebinar withCalendarId(@Nullable String calendarId) {
        this.calendarId = calendarId;
        return this;
    }


    public CalendarWebinar withCapacity(@Nullable Double capacity) {
        this.capacity = capacity;
        return this;
    }


    public CalendarWebinar withConference(@Nullable List<CalendarConference> conference) {
        this.conference = conference;
        return this;
    }


    public CalendarWebinar withCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }


    public CalendarWebinar withEndAt(@Nullable OffsetDateTime endAt) {
        this.endAt = endAt;
        return this;
    }


    public CalendarWebinar withHasPolls(@Nullable Boolean hasPolls) {
        this.hasPolls = hasPolls;
        return this;
    }


    public CalendarWebinar withHasQa(@Nullable Boolean hasQa) {
        this.hasQa = hasQa;
        return this;
    }


    public CalendarWebinar withHasRecording(@Nullable Boolean hasRecording) {
        this.hasRecording = hasRecording;
        return this;
    }


    public CalendarWebinar withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    public CalendarWebinar withIsAutoApprove(@Nullable Boolean isAutoApprove) {
        this.isAutoApprove = isAutoApprove;
        return this;
    }


    public CalendarWebinar withIsEnabled(@Nullable Boolean isEnabled) {
        this.isEnabled = isEnabled;
        return this;
    }


    public CalendarWebinar withIsWebcast(@Nullable Boolean isWebcast) {
        this.isWebcast = isWebcast;
        return this;
    }


    public CalendarWebinar withJoinUrl(@Nullable String joinUrl) {
        this.joinUrl = joinUrl;
        return this;
    }


    public CalendarWebinar withNotes(@Nullable String notes) {
        this.notes = notes;
        return this;
    }


    public CalendarWebinar withOrganizer(@Nullable PropertyCalendarWebinarOrganizer organizer) {
        this.organizer = organizer;
        return this;
    }


    public CalendarWebinar withPanelistPassword(@Nullable String panelistPassword) {
        this.panelistPassword = panelistPassword;
        return this;
    }


    public CalendarWebinar withPanelists(@Nullable List<CalendarWebinarPanelist> panelists) {
        this.panelists = panelists;
        return this;
    }


    public CalendarWebinar withRaw(@Nullable Map<String, Object> raw) {
        this.raw = raw;
        return this;
    }


    public CalendarWebinar withRecurrence(@Nullable List<CalendarEventRecurrence> recurrence) {
        this.recurrence = recurrence;
        return this;
    }


    public CalendarWebinar withRegistrantPassword(@Nullable String registrantPassword) {
        this.registrantPassword = registrantPassword;
        return this;
    }


    public CalendarWebinar withRegistrants(@Nullable List<CalendarWebinarRegistrant> registrants) {
        this.registrants = registrants;
        return this;
    }


    public CalendarWebinar withRequireAddress(@Nullable Boolean requireAddress) {
        this.requireAddress = requireAddress;
        return this;
    }


    public CalendarWebinar withRequireCompany(@Nullable Boolean requireCompany) {
        this.requireCompany = requireCompany;
        return this;
    }


    public CalendarWebinar withRequireEmail(@Nullable Boolean requireEmail) {
        this.requireEmail = requireEmail;
        return this;
    }


    public CalendarWebinar withRequireFirstName(@Nullable Boolean requireFirstName) {
        this.requireFirstName = requireFirstName;
        return this;
    }


    public CalendarWebinar withRequireJobTitle(@Nullable Boolean requireJobTitle) {
        this.requireJobTitle = requireJobTitle;
        return this;
    }


    public CalendarWebinar withRequireLastName(@Nullable Boolean requireLastName) {
        this.requireLastName = requireLastName;
        return this;
    }


    public CalendarWebinar withRequirePhone(@Nullable Boolean requirePhone) {
        this.requirePhone = requirePhone;
        return this;
    }


    public CalendarWebinar withStartAt(@Nullable OffsetDateTime startAt) {
        this.startAt = startAt;
        return this;
    }


    public CalendarWebinar withStatus(@Nullable CalendarWebinarStatus status) {
        this.status = status;
        return this;
    }


    public CalendarWebinar withSubject(@Nullable String subject) {
        this.subject = subject;
        return this;
    }


    public CalendarWebinar withTimezone(@Nullable String timezone) {
        this.timezone = timezone;
        return this;
    }


    public CalendarWebinar withUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }


    public CalendarWebinar withWebUrl(@Nullable String webUrl) {
        this.webUrl = webUrl;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CalendarWebinar other = (CalendarWebinar) o;
        return 
            Utils.enhancedDeepEquals(this.calendarId, other.calendarId) &&
            Utils.enhancedDeepEquals(this.capacity, other.capacity) &&
            Utils.enhancedDeepEquals(this.conference, other.conference) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.endAt, other.endAt) &&
            Utils.enhancedDeepEquals(this.hasPolls, other.hasPolls) &&
            Utils.enhancedDeepEquals(this.hasQa, other.hasQa) &&
            Utils.enhancedDeepEquals(this.hasRecording, other.hasRecording) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.isAutoApprove, other.isAutoApprove) &&
            Utils.enhancedDeepEquals(this.isEnabled, other.isEnabled) &&
            Utils.enhancedDeepEquals(this.isWebcast, other.isWebcast) &&
            Utils.enhancedDeepEquals(this.joinUrl, other.joinUrl) &&
            Utils.enhancedDeepEquals(this.notes, other.notes) &&
            Utils.enhancedDeepEquals(this.organizer, other.organizer) &&
            Utils.enhancedDeepEquals(this.panelistPassword, other.panelistPassword) &&
            Utils.enhancedDeepEquals(this.panelists, other.panelists) &&
            Utils.enhancedDeepEquals(this.raw, other.raw) &&
            Utils.enhancedDeepEquals(this.recurrence, other.recurrence) &&
            Utils.enhancedDeepEquals(this.registrantPassword, other.registrantPassword) &&
            Utils.enhancedDeepEquals(this.registrants, other.registrants) &&
            Utils.enhancedDeepEquals(this.requireAddress, other.requireAddress) &&
            Utils.enhancedDeepEquals(this.requireCompany, other.requireCompany) &&
            Utils.enhancedDeepEquals(this.requireEmail, other.requireEmail) &&
            Utils.enhancedDeepEquals(this.requireFirstName, other.requireFirstName) &&
            Utils.enhancedDeepEquals(this.requireJobTitle, other.requireJobTitle) &&
            Utils.enhancedDeepEquals(this.requireLastName, other.requireLastName) &&
            Utils.enhancedDeepEquals(this.requirePhone, other.requirePhone) &&
            Utils.enhancedDeepEquals(this.startAt, other.startAt) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.subject, other.subject) &&
            Utils.enhancedDeepEquals(this.timezone, other.timezone) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt) &&
            Utils.enhancedDeepEquals(this.webUrl, other.webUrl);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            calendarId, capacity, conference,
            createdAt, endAt, hasPolls,
            hasQa, hasRecording, id,
            isAutoApprove, isEnabled, isWebcast,
            joinUrl, notes, organizer,
            panelistPassword, panelists, raw,
            recurrence, registrantPassword, registrants,
            requireAddress, requireCompany, requireEmail,
            requireFirstName, requireJobTitle, requireLastName,
            requirePhone, startAt, status,
            subject, timezone, updatedAt,
            webUrl);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CalendarWebinar.class,
                "calendarId", calendarId,
                "capacity", capacity,
                "conference", conference,
                "createdAt", createdAt,
                "endAt", endAt,
                "hasPolls", hasPolls,
                "hasQa", hasQa,
                "hasRecording", hasRecording,
                "id", id,
                "isAutoApprove", isAutoApprove,
                "isEnabled", isEnabled,
                "isWebcast", isWebcast,
                "joinUrl", joinUrl,
                "notes", notes,
                "organizer", organizer,
                "panelistPassword", panelistPassword,
                "panelists", panelists,
                "raw", raw,
                "recurrence", recurrence,
                "registrantPassword", registrantPassword,
                "registrants", registrants,
                "requireAddress", requireAddress,
                "requireCompany", requireCompany,
                "requireEmail", requireEmail,
                "requireFirstName", requireFirstName,
                "requireJobTitle", requireJobTitle,
                "requireLastName", requireLastName,
                "requirePhone", requirePhone,
                "startAt", startAt,
                "status", status,
                "subject", subject,
                "timezone", timezone,
                "updatedAt", updatedAt,
                "webUrl", webUrl);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String calendarId;

        private Double capacity;

        private List<CalendarConference> conference;

        private OffsetDateTime createdAt;

        private OffsetDateTime endAt;

        private Boolean hasPolls;

        private Boolean hasQa;

        private Boolean hasRecording;

        private String id;

        private Boolean isAutoApprove;

        private Boolean isEnabled;

        private Boolean isWebcast;

        private String joinUrl;

        private String notes;

        private PropertyCalendarWebinarOrganizer organizer;

        private String panelistPassword;

        private List<CalendarWebinarPanelist> panelists;

        private Map<String, Object> raw;

        private List<CalendarEventRecurrence> recurrence;

        private String registrantPassword;

        private List<CalendarWebinarRegistrant> registrants;

        private Boolean requireAddress;

        private Boolean requireCompany;

        private Boolean requireEmail;

        private Boolean requireFirstName;

        private Boolean requireJobTitle;

        private Boolean requireLastName;

        private Boolean requirePhone;

        private OffsetDateTime startAt;

        private CalendarWebinarStatus status;

        private String subject;

        private String timezone;

        private OffsetDateTime updatedAt;

        private String webUrl;

        private Builder() {
          // force use of static builder() method
        }

        public Builder calendarId(@Nullable String calendarId) {
            this.calendarId = calendarId;
            return this;
        }

        public Builder capacity(@Nullable Double capacity) {
            this.capacity = capacity;
            return this;
        }

        public Builder conference(@Nullable List<CalendarConference> conference) {
            this.conference = conference;
            return this;
        }

        public Builder createdAt(@Nullable OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder endAt(@Nullable OffsetDateTime endAt) {
            this.endAt = endAt;
            return this;
        }

        public Builder hasPolls(@Nullable Boolean hasPolls) {
            this.hasPolls = hasPolls;
            return this;
        }

        public Builder hasQa(@Nullable Boolean hasQa) {
            this.hasQa = hasQa;
            return this;
        }

        public Builder hasRecording(@Nullable Boolean hasRecording) {
            this.hasRecording = hasRecording;
            return this;
        }

        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public Builder isAutoApprove(@Nullable Boolean isAutoApprove) {
            this.isAutoApprove = isAutoApprove;
            return this;
        }

        public Builder isEnabled(@Nullable Boolean isEnabled) {
            this.isEnabled = isEnabled;
            return this;
        }

        public Builder isWebcast(@Nullable Boolean isWebcast) {
            this.isWebcast = isWebcast;
            return this;
        }

        public Builder joinUrl(@Nullable String joinUrl) {
            this.joinUrl = joinUrl;
            return this;
        }

        public Builder notes(@Nullable String notes) {
            this.notes = notes;
            return this;
        }

        public Builder organizer(@Nullable PropertyCalendarWebinarOrganizer organizer) {
            this.organizer = organizer;
            return this;
        }

        public Builder panelistPassword(@Nullable String panelistPassword) {
            this.panelistPassword = panelistPassword;
            return this;
        }

        public Builder panelists(@Nullable List<CalendarWebinarPanelist> panelists) {
            this.panelists = panelists;
            return this;
        }

        public Builder raw(@Nullable Map<String, Object> raw) {
            this.raw = raw;
            return this;
        }

        public Builder recurrence(@Nullable List<CalendarEventRecurrence> recurrence) {
            this.recurrence = recurrence;
            return this;
        }

        public Builder registrantPassword(@Nullable String registrantPassword) {
            this.registrantPassword = registrantPassword;
            return this;
        }

        public Builder registrants(@Nullable List<CalendarWebinarRegistrant> registrants) {
            this.registrants = registrants;
            return this;
        }

        public Builder requireAddress(@Nullable Boolean requireAddress) {
            this.requireAddress = requireAddress;
            return this;
        }

        public Builder requireCompany(@Nullable Boolean requireCompany) {
            this.requireCompany = requireCompany;
            return this;
        }

        public Builder requireEmail(@Nullable Boolean requireEmail) {
            this.requireEmail = requireEmail;
            return this;
        }

        public Builder requireFirstName(@Nullable Boolean requireFirstName) {
            this.requireFirstName = requireFirstName;
            return this;
        }

        public Builder requireJobTitle(@Nullable Boolean requireJobTitle) {
            this.requireJobTitle = requireJobTitle;
            return this;
        }

        public Builder requireLastName(@Nullable Boolean requireLastName) {
            this.requireLastName = requireLastName;
            return this;
        }

        public Builder requirePhone(@Nullable Boolean requirePhone) {
            this.requirePhone = requirePhone;
            return this;
        }

        public Builder startAt(@Nullable OffsetDateTime startAt) {
            this.startAt = startAt;
            return this;
        }

        public Builder status(@Nullable CalendarWebinarStatus status) {
            this.status = status;
            return this;
        }

        public Builder subject(@Nullable String subject) {
            this.subject = subject;
            return this;
        }

        public Builder timezone(@Nullable String timezone) {
            this.timezone = timezone;
            return this;
        }

        public Builder updatedAt(@Nullable OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder webUrl(@Nullable String webUrl) {
            this.webUrl = webUrl;
            return this;
        }

        public CalendarWebinar build() {
            return new CalendarWebinar(
                calendarId, capacity, conference,
                createdAt, endAt, hasPolls,
                hasQa, hasRecording, id,
                isAutoApprove, isEnabled, isWebcast,
                joinUrl, notes, organizer,
                panelistPassword, panelists, raw,
                recurrence, registrantPassword, registrants,
                requireAddress, requireCompany, requireEmail,
                requireFirstName, requireJobTitle, requireLastName,
                requirePhone, startAt, status,
                subject, timezone, updatedAt,
                webUrl);
        }

    }
}
