/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class CdpProfile {
    /**
     * The address of the profile
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    private PropertyCdpProfileAddress address;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("birthdate")
    private String birthdate;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company")
    private String company;

    /**
     * The consent/privacy preferences of the profile
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("consent")
    private List<CdpConsent> consent;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    private OffsetDateTime createdAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private String email;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    private String firstName;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("gender")
    private CdpProfileGender gender;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * The typed identifiers stitched to this profile
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifiers")
    private List<CdpIdentifier> identifiers;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_anonymous")
    private Boolean isAnonymous;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    private String lastName;

    /**
     * The traits/attributes of the profile
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private List<CdpMetadata> metadata;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("raw")
    private Map<String, Object> raw;

    /**
     * The segments/audiences this profile currently belongs to
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("segments")
    private List<CdpProfileSegment> segments;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("source_id")
    private String sourceId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("telephone")
    private String telephone;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private String title;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updated_at")
    private OffsetDateTime updatedAt;

    @JsonCreator
    public CdpProfile(
            @JsonProperty("address") @Nullable PropertyCdpProfileAddress address,
            @JsonProperty("birthdate") @Nullable String birthdate,
            @JsonProperty("company") @Nullable String company,
            @JsonProperty("consent") @Nullable List<CdpConsent> consent,
            @JsonProperty("created_at") @Nullable OffsetDateTime createdAt,
            @JsonProperty("email") @Nullable String email,
            @JsonProperty("first_name") @Nullable String firstName,
            @JsonProperty("gender") @Nullable CdpProfileGender gender,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("identifiers") @Nullable List<CdpIdentifier> identifiers,
            @JsonProperty("is_anonymous") @Nullable Boolean isAnonymous,
            @JsonProperty("last_name") @Nullable String lastName,
            @JsonProperty("metadata") @Nullable List<CdpMetadata> metadata,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("raw") @Nullable Map<String, Object> raw,
            @JsonProperty("segments") @Nullable List<CdpProfileSegment> segments,
            @JsonProperty("source_id") @Nullable String sourceId,
            @JsonProperty("telephone") @Nullable String telephone,
            @JsonProperty("title") @Nullable String title,
            @JsonProperty("updated_at") @Nullable OffsetDateTime updatedAt) {
        this.address = address;
        this.birthdate = birthdate;
        this.company = company;
        this.consent = consent;
        this.createdAt = createdAt;
        this.email = email;
        this.firstName = firstName;
        this.gender = gender;
        this.id = id;
        this.identifiers = identifiers;
        this.isAnonymous = isAnonymous;
        this.lastName = lastName;
        this.metadata = metadata;
        this.name = name;
        this.raw = raw;
        this.segments = segments;
        this.sourceId = sourceId;
        this.telephone = telephone;
        this.title = title;
        this.updatedAt = updatedAt;
    }
    
    public CdpProfile() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * The address of the profile
     */
    public Optional<PropertyCdpProfileAddress> address() {
        return Optional.ofNullable(this.address);
    }

    public Optional<String> birthdate() {
        return Optional.ofNullable(this.birthdate);
    }

    public Optional<String> company() {
        return Optional.ofNullable(this.company);
    }

    /**
     * The consent/privacy preferences of the profile
     */
    public Optional<List<CdpConsent>> consent() {
        return Optional.ofNullable(this.consent);
    }

    public Optional<OffsetDateTime> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    public Optional<String> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    public Optional<CdpProfileGender> gender() {
        return Optional.ofNullable(this.gender);
    }

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The typed identifiers stitched to this profile
     */
    public Optional<List<CdpIdentifier>> identifiers() {
        return Optional.ofNullable(this.identifiers);
    }

    public Optional<Boolean> isAnonymous() {
        return Optional.ofNullable(this.isAnonymous);
    }

    public Optional<String> lastName() {
        return Optional.ofNullable(this.lastName);
    }

    /**
     * The traits/attributes of the profile
     */
    public Optional<List<CdpMetadata>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public Optional<Map<String, Object>> raw() {
        return Optional.ofNullable(this.raw);
    }

    /**
     * The segments/audiences this profile currently belongs to
     */
    public Optional<List<CdpProfileSegment>> segments() {
        return Optional.ofNullable(this.segments);
    }

    public Optional<String> sourceId() {
        return Optional.ofNullable(this.sourceId);
    }

    public Optional<String> telephone() {
        return Optional.ofNullable(this.telephone);
    }

    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }

    public Optional<OffsetDateTime> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The address of the profile
     */
    public CdpProfile withAddress(@Nullable PropertyCdpProfileAddress address) {
        this.address = address;
        return this;
    }


    public CdpProfile withBirthdate(@Nullable String birthdate) {
        this.birthdate = birthdate;
        return this;
    }


    public CdpProfile withCompany(@Nullable String company) {
        this.company = company;
        return this;
    }


    /**
     * The consent/privacy preferences of the profile
     */
    public CdpProfile withConsent(@Nullable List<CdpConsent> consent) {
        this.consent = consent;
        return this;
    }


    public CdpProfile withCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }


    public CdpProfile withEmail(@Nullable String email) {
        this.email = email;
        return this;
    }


    public CdpProfile withFirstName(@Nullable String firstName) {
        this.firstName = firstName;
        return this;
    }


    public CdpProfile withGender(@Nullable CdpProfileGender gender) {
        this.gender = gender;
        return this;
    }


    public CdpProfile withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * The typed identifiers stitched to this profile
     */
    public CdpProfile withIdentifiers(@Nullable List<CdpIdentifier> identifiers) {
        this.identifiers = identifiers;
        return this;
    }


    public CdpProfile withIsAnonymous(@Nullable Boolean isAnonymous) {
        this.isAnonymous = isAnonymous;
        return this;
    }


    public CdpProfile withLastName(@Nullable String lastName) {
        this.lastName = lastName;
        return this;
    }


    /**
     * The traits/attributes of the profile
     */
    public CdpProfile withMetadata(@Nullable List<CdpMetadata> metadata) {
        this.metadata = metadata;
        return this;
    }


    public CdpProfile withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    public CdpProfile withRaw(@Nullable Map<String, Object> raw) {
        this.raw = raw;
        return this;
    }


    /**
     * The segments/audiences this profile currently belongs to
     */
    public CdpProfile withSegments(@Nullable List<CdpProfileSegment> segments) {
        this.segments = segments;
        return this;
    }


    public CdpProfile withSourceId(@Nullable String sourceId) {
        this.sourceId = sourceId;
        return this;
    }


    public CdpProfile withTelephone(@Nullable String telephone) {
        this.telephone = telephone;
        return this;
    }


    public CdpProfile withTitle(@Nullable String title) {
        this.title = title;
        return this;
    }


    public CdpProfile withUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CdpProfile other = (CdpProfile) o;
        return 
            Utils.enhancedDeepEquals(this.address, other.address) &&
            Utils.enhancedDeepEquals(this.birthdate, other.birthdate) &&
            Utils.enhancedDeepEquals(this.company, other.company) &&
            Utils.enhancedDeepEquals(this.consent, other.consent) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.firstName, other.firstName) &&
            Utils.enhancedDeepEquals(this.gender, other.gender) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.identifiers, other.identifiers) &&
            Utils.enhancedDeepEquals(this.isAnonymous, other.isAnonymous) &&
            Utils.enhancedDeepEquals(this.lastName, other.lastName) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.raw, other.raw) &&
            Utils.enhancedDeepEquals(this.segments, other.segments) &&
            Utils.enhancedDeepEquals(this.sourceId, other.sourceId) &&
            Utils.enhancedDeepEquals(this.telephone, other.telephone) &&
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            address, birthdate, company,
            consent, createdAt, email,
            firstName, gender, id,
            identifiers, isAnonymous, lastName,
            metadata, name, raw,
            segments, sourceId, telephone,
            title, updatedAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CdpProfile.class,
                "address", address,
                "birthdate", birthdate,
                "company", company,
                "consent", consent,
                "createdAt", createdAt,
                "email", email,
                "firstName", firstName,
                "gender", gender,
                "id", id,
                "identifiers", identifiers,
                "isAnonymous", isAnonymous,
                "lastName", lastName,
                "metadata", metadata,
                "name", name,
                "raw", raw,
                "segments", segments,
                "sourceId", sourceId,
                "telephone", telephone,
                "title", title,
                "updatedAt", updatedAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PropertyCdpProfileAddress address;

        private String birthdate;

        private String company;

        private List<CdpConsent> consent;

        private OffsetDateTime createdAt;

        private String email;

        private String firstName;

        private CdpProfileGender gender;

        private String id;

        private List<CdpIdentifier> identifiers;

        private Boolean isAnonymous;

        private String lastName;

        private List<CdpMetadata> metadata;

        private String name;

        private Map<String, Object> raw;

        private List<CdpProfileSegment> segments;

        private String sourceId;

        private String telephone;

        private String title;

        private OffsetDateTime updatedAt;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The address of the profile
         */
        public Builder address(@Nullable PropertyCdpProfileAddress address) {
            this.address = address;
            return this;
        }

        public Builder birthdate(@Nullable String birthdate) {
            this.birthdate = birthdate;
            return this;
        }

        public Builder company(@Nullable String company) {
            this.company = company;
            return this;
        }

        /**
         * The consent/privacy preferences of the profile
         */
        public Builder consent(@Nullable List<CdpConsent> consent) {
            this.consent = consent;
            return this;
        }

        public Builder createdAt(@Nullable OffsetDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder email(@Nullable String email) {
            this.email = email;
            return this;
        }

        public Builder firstName(@Nullable String firstName) {
            this.firstName = firstName;
            return this;
        }

        public Builder gender(@Nullable CdpProfileGender gender) {
            this.gender = gender;
            return this;
        }

        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * The typed identifiers stitched to this profile
         */
        public Builder identifiers(@Nullable List<CdpIdentifier> identifiers) {
            this.identifiers = identifiers;
            return this;
        }

        public Builder isAnonymous(@Nullable Boolean isAnonymous) {
            this.isAnonymous = isAnonymous;
            return this;
        }

        public Builder lastName(@Nullable String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * The traits/attributes of the profile
         */
        public Builder metadata(@Nullable List<CdpMetadata> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        public Builder raw(@Nullable Map<String, Object> raw) {
            this.raw = raw;
            return this;
        }

        /**
         * The segments/audiences this profile currently belongs to
         */
        public Builder segments(@Nullable List<CdpProfileSegment> segments) {
            this.segments = segments;
            return this;
        }

        public Builder sourceId(@Nullable String sourceId) {
            this.sourceId = sourceId;
            return this;
        }

        public Builder telephone(@Nullable String telephone) {
            this.telephone = telephone;
            return this;
        }

        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        public Builder updatedAt(@Nullable OffsetDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public CdpProfile build() {
            return new CdpProfile(
                address, birthdate, company,
                consent, createdAt, email,
                firstName, gender, id,
                identifiers, isAnonymous, lastName,
                metadata, name, raw,
                segments, sourceId, telephone,
                title, updatedAt);
        }

    }
}
