/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class CommerceItemMediaType {

    public static final CommerceItemMediaType IMAGE = new CommerceItemMediaType("image");
    public static final CommerceItemMediaType VIDEO = new CommerceItemMediaType("video");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CommerceItemMediaType> values = createValuesMap();
    private static final Map<String, CommerceItemMediaTypeEnum> enums = createEnumsMap();

    private final String value;

    private CommerceItemMediaType(String value) {
        this.value = value;
    }

    /**
     * Returns a CommerceItemMediaType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CommerceItemMediaType
     */ 
    @JsonCreator
    public static CommerceItemMediaType of(String value) {
        synchronized (CommerceItemMediaType.class) {
            return values.computeIfAbsent(value, v -> new CommerceItemMediaType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CommerceItemMediaTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CommerceItemMediaType other = (CommerceItemMediaType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CommerceItemMediaType [value=" + value + "]";
    }

    // return an array just like an enum
    public static CommerceItemMediaType[] values() {
        synchronized (CommerceItemMediaType.class) {
            return values.values().toArray(new CommerceItemMediaType[] {});
        }
    }

    private static final Map<String, CommerceItemMediaType> createValuesMap() {
        Map<String, CommerceItemMediaType> map = new LinkedHashMap<>();
        map.put("image", IMAGE);
        map.put("video", VIDEO);
        return map;
    }

    private static final Map<String, CommerceItemMediaTypeEnum> createEnumsMap() {
        Map<String, CommerceItemMediaTypeEnum> map = new HashMap<>();
        map.put("image", CommerceItemMediaTypeEnum.IMAGE);
        map.put("video", CommerceItemMediaTypeEnum.VIDEO);
        return map;
    }
    
    
    public enum CommerceItemMediaTypeEnum {

        IMAGE("image"),
        VIDEO("video"),;

        private final String value;

        private CommerceItemMediaTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

