/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class CrmEventFormOption {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("label")
    private String label;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private String value;

    @JsonCreator
    public CrmEventFormOption(
            @JsonProperty("label") @Nullable String label,
            @JsonProperty("value") @Nullable String value) {
        this.label = label;
        this.value = value;
    }
    
    public CrmEventFormOption() {
        this(null, null);
    }

    public Optional<String> label() {
        return Optional.ofNullable(this.label);
    }

    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }


    public CrmEventFormOption withLabel(@Nullable String label) {
        this.label = label;
        return this;
    }


    public CrmEventFormOption withValue(@Nullable String value) {
        this.value = value;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CrmEventFormOption other = (CrmEventFormOption) o;
        return 
            Utils.enhancedDeepEquals(this.label, other.label) &&
            Utils.enhancedDeepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            label, value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CrmEventFormOption.class,
                "label", label,
                "value", value);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String label;

        private String value;

        private Builder() {
          // force use of static builder() method
        }

        public Builder label(@Nullable String label) {
            this.label = label;
            return this;
        }

        public Builder value(@Nullable String value) {
            this.value = value;
            return this;
        }

        public CrmEventFormOption build() {
            return new CrmEventFormOption(
                label, value);
        }

    }
}
