/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class PropertyAdsReportMetricsCampaignKpiType {

    public static final PropertyAdsReportMetricsCampaignKpiType UNSPECIFIED = new PropertyAdsReportMetricsCampaignKpiType("UNSPECIFIED");
    public static final PropertyAdsReportMetricsCampaignKpiType CPM = new PropertyAdsReportMetricsCampaignKpiType("CPM");
    public static final PropertyAdsReportMetricsCampaignKpiType CPC = new PropertyAdsReportMetricsCampaignKpiType("CPC");
    public static final PropertyAdsReportMetricsCampaignKpiType CPA = new PropertyAdsReportMetricsCampaignKpiType("CPA");
    public static final PropertyAdsReportMetricsCampaignKpiType CTR = new PropertyAdsReportMetricsCampaignKpiType("CTR");
    public static final PropertyAdsReportMetricsCampaignKpiType VIEWABILITY = new PropertyAdsReportMetricsCampaignKpiType("VIEWABILITY");
    public static final PropertyAdsReportMetricsCampaignKpiType CPIAVC = new PropertyAdsReportMetricsCampaignKpiType("CPIAVC");
    public static final PropertyAdsReportMetricsCampaignKpiType CPE = new PropertyAdsReportMetricsCampaignKpiType("CPE");
    public static final PropertyAdsReportMetricsCampaignKpiType CPV = new PropertyAdsReportMetricsCampaignKpiType("CPV");
    public static final PropertyAdsReportMetricsCampaignKpiType CLICK_CVR = new PropertyAdsReportMetricsCampaignKpiType("CLICK_CVR");
    public static final PropertyAdsReportMetricsCampaignKpiType IMPRESSION_CVR = new PropertyAdsReportMetricsCampaignKpiType("IMPRESSION_CVR");
    public static final PropertyAdsReportMetricsCampaignKpiType VCPM = new PropertyAdsReportMetricsCampaignKpiType("VCPM");
    public static final PropertyAdsReportMetricsCampaignKpiType VTR = new PropertyAdsReportMetricsCampaignKpiType("VTR");
    public static final PropertyAdsReportMetricsCampaignKpiType AUDIO_COMPLETION_RATE = new PropertyAdsReportMetricsCampaignKpiType("AUDIO_COMPLETION_RATE");
    public static final PropertyAdsReportMetricsCampaignKpiType VIDEO_COMPLETION_RATE = new PropertyAdsReportMetricsCampaignKpiType("VIDEO_COMPLETION_RATE");
    public static final PropertyAdsReportMetricsCampaignKpiType CPCL = new PropertyAdsReportMetricsCampaignKpiType("CPCL");
    public static final PropertyAdsReportMetricsCampaignKpiType CPCV = new PropertyAdsReportMetricsCampaignKpiType("CPCV");
    public static final PropertyAdsReportMetricsCampaignKpiType TOS10 = new PropertyAdsReportMetricsCampaignKpiType("TOS10");
    public static final PropertyAdsReportMetricsCampaignKpiType MAXIMIZE_PACING = new PropertyAdsReportMetricsCampaignKpiType("MAXIMIZE_PACING");
    public static final PropertyAdsReportMetricsCampaignKpiType CUSTOM_IMPRESSION_VALUE_OVER_COST = new PropertyAdsReportMetricsCampaignKpiType("CUSTOM_IMPRESSION_VALUE_OVER_COST");
    public static final PropertyAdsReportMetricsCampaignKpiType OTHER = new PropertyAdsReportMetricsCampaignKpiType("OTHER");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PropertyAdsReportMetricsCampaignKpiType> values = createValuesMap();
    private static final Map<String, PropertyAdsReportMetricsCampaignKpiTypeEnum> enums = createEnumsMap();

    private final String value;

    private PropertyAdsReportMetricsCampaignKpiType(String value) {
        this.value = value;
    }

    /**
     * Returns a PropertyAdsReportMetricsCampaignKpiType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PropertyAdsReportMetricsCampaignKpiType
     */ 
    @JsonCreator
    public static PropertyAdsReportMetricsCampaignKpiType of(String value) {
        synchronized (PropertyAdsReportMetricsCampaignKpiType.class) {
            return values.computeIfAbsent(value, v -> new PropertyAdsReportMetricsCampaignKpiType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PropertyAdsReportMetricsCampaignKpiTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PropertyAdsReportMetricsCampaignKpiType other = (PropertyAdsReportMetricsCampaignKpiType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PropertyAdsReportMetricsCampaignKpiType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PropertyAdsReportMetricsCampaignKpiType[] values() {
        synchronized (PropertyAdsReportMetricsCampaignKpiType.class) {
            return values.values().toArray(new PropertyAdsReportMetricsCampaignKpiType[] {});
        }
    }

    private static final Map<String, PropertyAdsReportMetricsCampaignKpiType> createValuesMap() {
        Map<String, PropertyAdsReportMetricsCampaignKpiType> map = new LinkedHashMap<>();
        map.put("UNSPECIFIED", UNSPECIFIED);
        map.put("CPM", CPM);
        map.put("CPC", CPC);
        map.put("CPA", CPA);
        map.put("CTR", CTR);
        map.put("VIEWABILITY", VIEWABILITY);
        map.put("CPIAVC", CPIAVC);
        map.put("CPE", CPE);
        map.put("CPV", CPV);
        map.put("CLICK_CVR", CLICK_CVR);
        map.put("IMPRESSION_CVR", IMPRESSION_CVR);
        map.put("VCPM", VCPM);
        map.put("VTR", VTR);
        map.put("AUDIO_COMPLETION_RATE", AUDIO_COMPLETION_RATE);
        map.put("VIDEO_COMPLETION_RATE", VIDEO_COMPLETION_RATE);
        map.put("CPCL", CPCL);
        map.put("CPCV", CPCV);
        map.put("TOS10", TOS10);
        map.put("MAXIMIZE_PACING", MAXIMIZE_PACING);
        map.put("CUSTOM_IMPRESSION_VALUE_OVER_COST", CUSTOM_IMPRESSION_VALUE_OVER_COST);
        map.put("OTHER", OTHER);
        return map;
    }

    private static final Map<String, PropertyAdsReportMetricsCampaignKpiTypeEnum> createEnumsMap() {
        Map<String, PropertyAdsReportMetricsCampaignKpiTypeEnum> map = new HashMap<>();
        map.put("UNSPECIFIED", PropertyAdsReportMetricsCampaignKpiTypeEnum.UNSPECIFIED);
        map.put("CPM", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPM);
        map.put("CPC", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPC);
        map.put("CPA", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPA);
        map.put("CTR", PropertyAdsReportMetricsCampaignKpiTypeEnum.CTR);
        map.put("VIEWABILITY", PropertyAdsReportMetricsCampaignKpiTypeEnum.VIEWABILITY);
        map.put("CPIAVC", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPIAVC);
        map.put("CPE", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPE);
        map.put("CPV", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPV);
        map.put("CLICK_CVR", PropertyAdsReportMetricsCampaignKpiTypeEnum.CLICK_CVR);
        map.put("IMPRESSION_CVR", PropertyAdsReportMetricsCampaignKpiTypeEnum.IMPRESSION_CVR);
        map.put("VCPM", PropertyAdsReportMetricsCampaignKpiTypeEnum.VCPM);
        map.put("VTR", PropertyAdsReportMetricsCampaignKpiTypeEnum.VTR);
        map.put("AUDIO_COMPLETION_RATE", PropertyAdsReportMetricsCampaignKpiTypeEnum.AUDIO_COMPLETION_RATE);
        map.put("VIDEO_COMPLETION_RATE", PropertyAdsReportMetricsCampaignKpiTypeEnum.VIDEO_COMPLETION_RATE);
        map.put("CPCL", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPCL);
        map.put("CPCV", PropertyAdsReportMetricsCampaignKpiTypeEnum.CPCV);
        map.put("TOS10", PropertyAdsReportMetricsCampaignKpiTypeEnum.TOS10);
        map.put("MAXIMIZE_PACING", PropertyAdsReportMetricsCampaignKpiTypeEnum.MAXIMIZE_PACING);
        map.put("CUSTOM_IMPRESSION_VALUE_OVER_COST", PropertyAdsReportMetricsCampaignKpiTypeEnum.CUSTOM_IMPRESSION_VALUE_OVER_COST);
        map.put("OTHER", PropertyAdsReportMetricsCampaignKpiTypeEnum.OTHER);
        return map;
    }
    
    
    public enum PropertyAdsReportMetricsCampaignKpiTypeEnum {

        UNSPECIFIED("UNSPECIFIED"),
        CPM("CPM"),
        CPC("CPC"),
        CPA("CPA"),
        CTR("CTR"),
        VIEWABILITY("VIEWABILITY"),
        CPIAVC("CPIAVC"),
        CPE("CPE"),
        CPV("CPV"),
        CLICK_CVR("CLICK_CVR"),
        IMPRESSION_CVR("IMPRESSION_CVR"),
        VCPM("VCPM"),
        VTR("VTR"),
        AUDIO_COMPLETION_RATE("AUDIO_COMPLETION_RATE"),
        VIDEO_COMPLETION_RATE("VIDEO_COMPLETION_RATE"),
        CPCL("CPCL"),
        CPCV("CPCV"),
        TOS10("TOS10"),
        MAXIMIZE_PACING("MAXIMIZE_PACING"),
        CUSTOM_IMPRESSION_VALUE_OVER_COST("CUSTOM_IMPRESSION_VALUE_OVER_COST"),
        OTHER("OTHER"),;

        private final String value;

        private PropertyAdsReportMetricsCampaignKpiTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

