/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class PropertyAdsReportMetricsAdAdType {

    public static final PropertyAdsReportMetricsAdAdType TEXT = new PropertyAdsReportMetricsAdAdType("TEXT");
    public static final PropertyAdsReportMetricsAdAdType IMAGE = new PropertyAdsReportMetricsAdAdType("IMAGE");
    public static final PropertyAdsReportMetricsAdAdType VIDEO = new PropertyAdsReportMetricsAdAdType("VIDEO");
    public static final PropertyAdsReportMetricsAdAdType RESPONSIVE = new PropertyAdsReportMetricsAdAdType("RESPONSIVE");
    public static final PropertyAdsReportMetricsAdAdType SHOPPING = new PropertyAdsReportMetricsAdAdType("SHOPPING");
    public static final PropertyAdsReportMetricsAdAdType APP = new PropertyAdsReportMetricsAdAdType("APP");
    public static final PropertyAdsReportMetricsAdAdType CALL = new PropertyAdsReportMetricsAdAdType("CALL");
    public static final PropertyAdsReportMetricsAdAdType CAROUSEL = new PropertyAdsReportMetricsAdAdType("CAROUSEL");
    public static final PropertyAdsReportMetricsAdAdType SOCIAL = new PropertyAdsReportMetricsAdAdType("SOCIAL");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PropertyAdsReportMetricsAdAdType> values = createValuesMap();
    private static final Map<String, PropertyAdsReportMetricsAdAdTypeEnum> enums = createEnumsMap();

    private final String value;

    private PropertyAdsReportMetricsAdAdType(String value) {
        this.value = value;
    }

    /**
     * Returns a PropertyAdsReportMetricsAdAdType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PropertyAdsReportMetricsAdAdType
     */ 
    @JsonCreator
    public static PropertyAdsReportMetricsAdAdType of(String value) {
        synchronized (PropertyAdsReportMetricsAdAdType.class) {
            return values.computeIfAbsent(value, v -> new PropertyAdsReportMetricsAdAdType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PropertyAdsReportMetricsAdAdTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PropertyAdsReportMetricsAdAdType other = (PropertyAdsReportMetricsAdAdType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PropertyAdsReportMetricsAdAdType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PropertyAdsReportMetricsAdAdType[] values() {
        synchronized (PropertyAdsReportMetricsAdAdType.class) {
            return values.values().toArray(new PropertyAdsReportMetricsAdAdType[] {});
        }
    }

    private static final Map<String, PropertyAdsReportMetricsAdAdType> createValuesMap() {
        Map<String, PropertyAdsReportMetricsAdAdType> map = new LinkedHashMap<>();
        map.put("TEXT", TEXT);
        map.put("IMAGE", IMAGE);
        map.put("VIDEO", VIDEO);
        map.put("RESPONSIVE", RESPONSIVE);
        map.put("SHOPPING", SHOPPING);
        map.put("APP", APP);
        map.put("CALL", CALL);
        map.put("CAROUSEL", CAROUSEL);
        map.put("SOCIAL", SOCIAL);
        return map;
    }

    private static final Map<String, PropertyAdsReportMetricsAdAdTypeEnum> createEnumsMap() {
        Map<String, PropertyAdsReportMetricsAdAdTypeEnum> map = new HashMap<>();
        map.put("TEXT", PropertyAdsReportMetricsAdAdTypeEnum.TEXT);
        map.put("IMAGE", PropertyAdsReportMetricsAdAdTypeEnum.IMAGE);
        map.put("VIDEO", PropertyAdsReportMetricsAdAdTypeEnum.VIDEO);
        map.put("RESPONSIVE", PropertyAdsReportMetricsAdAdTypeEnum.RESPONSIVE);
        map.put("SHOPPING", PropertyAdsReportMetricsAdAdTypeEnum.SHOPPING);
        map.put("APP", PropertyAdsReportMetricsAdAdTypeEnum.APP);
        map.put("CALL", PropertyAdsReportMetricsAdAdTypeEnum.CALL);
        map.put("CAROUSEL", PropertyAdsReportMetricsAdAdTypeEnum.CAROUSEL);
        map.put("SOCIAL", PropertyAdsReportMetricsAdAdTypeEnum.SOCIAL);
        return map;
    }
    
    
    public enum PropertyAdsReportMetricsAdAdTypeEnum {

        TEXT("TEXT"),
        IMAGE("IMAGE"),
        VIDEO("VIDEO"),
        RESPONSIVE("RESPONSIVE"),
        SHOPPING("SHOPPING"),
        APP("APP"),
        CALL("CALL"),
        CAROUSEL("CAROUSEL"),
        SOCIAL("SOCIAL"),;

        private final String value;

        private PropertyAdsReportMetricsAdAdTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

