/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.ShippingLabel;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class CreateShippingLabelRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private ShippingLabel shippingLabel;

    /**
     * ID of the connection
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connection_id")
    private String connectionId;

    /**
     * Fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    private Optional<? extends List<CreateShippingLabelQueryParamFields>> fields;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=raw")
    private Optional<String> raw;

    @JsonCreator
    public CreateShippingLabelRequest(
            ShippingLabel shippingLabel,
            String connectionId,
            Optional<? extends List<CreateShippingLabelQueryParamFields>> fields,
            Optional<String> raw) {
        Utils.checkNotNull(shippingLabel, "shippingLabel");
        Utils.checkNotNull(connectionId, "connectionId");
        Utils.checkNotNull(fields, "fields");
        Utils.checkNotNull(raw, "raw");
        this.shippingLabel = shippingLabel;
        this.connectionId = connectionId;
        this.fields = fields;
        this.raw = raw;
    }
    
    public CreateShippingLabelRequest(
            ShippingLabel shippingLabel,
            String connectionId) {
        this(shippingLabel, connectionId, Optional.empty(),
            Optional.empty());
    }

    @JsonIgnore
    public ShippingLabel shippingLabel() {
        return shippingLabel;
    }

    /**
     * ID of the connection
     */
    @JsonIgnore
    public String connectionId() {
        return connectionId;
    }

    /**
     * Fields to return
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<CreateShippingLabelQueryParamFields>> fields() {
        return (Optional<List<CreateShippingLabelQueryParamFields>>) fields;
    }

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    @JsonIgnore
    public Optional<String> raw() {
        return raw;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateShippingLabelRequest withShippingLabel(ShippingLabel shippingLabel) {
        Utils.checkNotNull(shippingLabel, "shippingLabel");
        this.shippingLabel = shippingLabel;
        return this;
    }

    /**
     * ID of the connection
     */
    public CreateShippingLabelRequest withConnectionId(String connectionId) {
        Utils.checkNotNull(connectionId, "connectionId");
        this.connectionId = connectionId;
        return this;
    }

    /**
     * Fields to return
     */
    public CreateShippingLabelRequest withFields(List<CreateShippingLabelQueryParamFields> fields) {
        Utils.checkNotNull(fields, "fields");
        this.fields = Optional.ofNullable(fields);
        return this;
    }


    /**
     * Fields to return
     */
    public CreateShippingLabelRequest withFields(Optional<? extends List<CreateShippingLabelQueryParamFields>> fields) {
        Utils.checkNotNull(fields, "fields");
        this.fields = fields;
        return this;
    }

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public CreateShippingLabelRequest withRaw(String raw) {
        Utils.checkNotNull(raw, "raw");
        this.raw = Optional.ofNullable(raw);
        return this;
    }


    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public CreateShippingLabelRequest withRaw(Optional<String> raw) {
        Utils.checkNotNull(raw, "raw");
        this.raw = raw;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateShippingLabelRequest other = (CreateShippingLabelRequest) o;
        return 
            Utils.enhancedDeepEquals(this.shippingLabel, other.shippingLabel) &&
            Utils.enhancedDeepEquals(this.connectionId, other.connectionId) &&
            Utils.enhancedDeepEquals(this.fields, other.fields) &&
            Utils.enhancedDeepEquals(this.raw, other.raw);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            shippingLabel, connectionId, fields,
            raw);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateShippingLabelRequest.class,
                "shippingLabel", shippingLabel,
                "connectionId", connectionId,
                "fields", fields,
                "raw", raw);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ShippingLabel shippingLabel;

        private String connectionId;

        private Optional<? extends List<CreateShippingLabelQueryParamFields>> fields = Optional.empty();

        private Optional<String> raw = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder shippingLabel(ShippingLabel shippingLabel) {
            Utils.checkNotNull(shippingLabel, "shippingLabel");
            this.shippingLabel = shippingLabel;
            return this;
        }


        /**
         * ID of the connection
         */
        public Builder connectionId(String connectionId) {
            Utils.checkNotNull(connectionId, "connectionId");
            this.connectionId = connectionId;
            return this;
        }


        /**
         * Fields to return
         */
        public Builder fields(List<CreateShippingLabelQueryParamFields> fields) {
            Utils.checkNotNull(fields, "fields");
            this.fields = Optional.ofNullable(fields);
            return this;
        }

        /**
         * Fields to return
         */
        public Builder fields(Optional<? extends List<CreateShippingLabelQueryParamFields>> fields) {
            Utils.checkNotNull(fields, "fields");
            this.fields = fields;
            return this;
        }


        /**
         * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
         * 
         * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
         */
        public Builder raw(String raw) {
            Utils.checkNotNull(raw, "raw");
            this.raw = Optional.ofNullable(raw);
            return this;
        }

        /**
         * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
         * 
         * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
         */
        public Builder raw(Optional<String> raw) {
            Utils.checkNotNull(raw, "raw");
            this.raw = raw;
            return this;
        }

        public CreateShippingLabelRequest build() {

            return new CreateShippingLabelRequest(
                shippingLabel, connectionId, fields,
                raw);
        }

    }
}
