/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.CreateCdpSource;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class CreateCdpSourceRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private CreateCdpSourceRequest request;

    public CreateCdpSourceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateCdpSourceRequestBuilder request(@Nonnull CreateCdpSourceRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private CreateCdpSourceRequest _buildRequest() {
        return this.request;
    }
    
    public CreateCdpSourceRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CreateCdpSourceResponse call() {
        RequestOperation<CreateCdpSourceRequest, CreateCdpSourceResponse> operation
              = new CreateCdpSource.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
