/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.GetClubsActivity2;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class GetClubsActivity2RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetClubsActivity2Request request;

    public GetClubsActivity2RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetClubsActivity2RequestBuilder request(@Nonnull GetClubsActivity2Request request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetClubsActivity2Request _buildRequest() {
        return this.request;
    }
    
    public GetClubsActivity2RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetClubsActivity2Response call() {
        RequestOperation<GetClubsActivity2Request, GetClubsActivity2Response> operation
              = new GetClubsActivity2.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
