/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.GetHrisPayslip;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class GetHrisPayslipRequestBuilder {

    private GetHrisPayslipRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetHrisPayslipRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetHrisPayslipRequestBuilder request(GetHrisPayslipRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetHrisPayslipResponse call() {
        
        RequestOperation<GetHrisPayslipRequest, GetHrisPayslipResponse> operation
              = new GetHrisPayslip.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
