/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import java.lang.Exception;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.GetUnifiedWebhookOperation;
import to.unified.unified_java_sdk.utils.Utils;

public class GetUnifiedWebhookRequestBuilder {

    private GetUnifiedWebhookRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetUnifiedWebhookRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetUnifiedWebhookRequestBuilder request(GetUnifiedWebhookRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetUnifiedWebhookResponse call() throws Exception {
        
        RequestOperation<GetUnifiedWebhookRequest, GetUnifiedWebhookResponse> operation
              = new GetUnifiedWebhookOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
