/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.ListAssessmentPackages;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class ListAssessmentPackagesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ListAssessmentPackagesRequest request;

    public ListAssessmentPackagesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListAssessmentPackagesRequestBuilder request(@Nonnull ListAssessmentPackagesRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private ListAssessmentPackagesRequest _buildRequest() {
        return this.request;
    }
    
    public ListAssessmentPackagesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ListAssessmentPackagesResponse call() {
        RequestOperation<ListAssessmentPackagesRequest, ListAssessmentPackagesResponse> operation
              = new ListAssessmentPackages.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
