/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.AccountingSalesorder;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class PatchAccountingSalesorderRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private AccountingSalesorder accountingSalesorder;

    /**
     * ID of the connection
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connection_id")
    private String connectionId;

    /**
     * Fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    private List<PatchAccountingSalesorderQueryParamFields> fields;

    /**
     * ID of the Salesorder
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=raw")
    private String raw;

    @JsonCreator
    public PatchAccountingSalesorderRequest(
            @Nonnull AccountingSalesorder accountingSalesorder,
            @Nonnull String connectionId,
            @Nullable List<PatchAccountingSalesorderQueryParamFields> fields,
            @Nonnull String id,
            @Nullable String raw) {
        this.accountingSalesorder = Optional.ofNullable(accountingSalesorder)
            .orElseThrow(() -> new IllegalArgumentException("accountingSalesorder cannot be null"));
        this.connectionId = Optional.ofNullable(connectionId)
            .orElseThrow(() -> new IllegalArgumentException("connectionId cannot be null"));
        this.fields = fields;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.raw = raw;
    }
    
    public PatchAccountingSalesorderRequest(
            @Nonnull AccountingSalesorder accountingSalesorder,
            @Nonnull String connectionId,
            @Nonnull String id) {
        this(accountingSalesorder, connectionId, null,
            id, null);
    }

    public AccountingSalesorder accountingSalesorder() {
        return this.accountingSalesorder;
    }

    /**
     * ID of the connection
     */
    public String connectionId() {
        return this.connectionId;
    }

    /**
     * Fields to return
     */
    public Optional<List<PatchAccountingSalesorderQueryParamFields>> fields() {
        return Optional.ofNullable(this.fields);
    }

    /**
     * ID of the Salesorder
     */
    public String id() {
        return this.id;
    }

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public Optional<String> raw() {
        return Optional.ofNullable(this.raw);
    }

    public static Builder builder() {
        return new Builder();
    }


    public PatchAccountingSalesorderRequest withAccountingSalesorder(@Nonnull AccountingSalesorder accountingSalesorder) {
        this.accountingSalesorder = Utils.checkNotNull(accountingSalesorder, "accountingSalesorder");
        return this;
    }


    /**
     * ID of the connection
     */
    public PatchAccountingSalesorderRequest withConnectionId(@Nonnull String connectionId) {
        this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
        return this;
    }


    /**
     * Fields to return
     */
    public PatchAccountingSalesorderRequest withFields(@Nullable List<PatchAccountingSalesorderQueryParamFields> fields) {
        this.fields = fields;
        return this;
    }


    /**
     * ID of the Salesorder
     */
    public PatchAccountingSalesorderRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public PatchAccountingSalesorderRequest withRaw(@Nullable String raw) {
        this.raw = raw;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchAccountingSalesorderRequest other = (PatchAccountingSalesorderRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountingSalesorder, other.accountingSalesorder) &&
            Utils.enhancedDeepEquals(this.connectionId, other.connectionId) &&
            Utils.enhancedDeepEquals(this.fields, other.fields) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.raw, other.raw);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountingSalesorder, connectionId, fields,
            id, raw);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PatchAccountingSalesorderRequest.class,
                "accountingSalesorder", accountingSalesorder,
                "connectionId", connectionId,
                "fields", fields,
                "id", id,
                "raw", raw);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AccountingSalesorder accountingSalesorder;

        private String connectionId;

        private List<PatchAccountingSalesorderQueryParamFields> fields;

        private String id;

        private String raw;

        private Builder() {
          // force use of static builder() method
        }

        public Builder accountingSalesorder(@Nonnull AccountingSalesorder accountingSalesorder) {
            this.accountingSalesorder = Utils.checkNotNull(accountingSalesorder, "accountingSalesorder");
            return this;
        }

        /**
         * ID of the connection
         */
        public Builder connectionId(@Nonnull String connectionId) {
            this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
            return this;
        }

        /**
         * Fields to return
         */
        public Builder fields(@Nullable List<PatchAccountingSalesorderQueryParamFields> fields) {
            this.fields = fields;
            return this;
        }

        /**
         * ID of the Salesorder
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
         * 
         * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
         */
        public Builder raw(@Nullable String raw) {
            this.raw = raw;
            return this;
        }

        public PatchAccountingSalesorderRequest build() {
            return new PatchAccountingSalesorderRequest(
                accountingSalesorder, connectionId, fields,
                id, raw);
        }

    }
}
