/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PatchTaskCommentQueryParamFields {
    ID("id"),
    CREATED_AT("created_at"),
    UPDATED_AT("updated_at"),
    TEXT("text"),
    USER_ID("user_id"),
    USER_NAME("user_name"),
    TASK_ID("task_id"),
    RAW("raw");

    @JsonValue
    private final String value;

    PatchTaskCommentQueryParamFields(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PatchTaskCommentQueryParamFields> fromValue(String value) {
        for (PatchTaskCommentQueryParamFields o: PatchTaskCommentQueryParamFields.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

