/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import java.lang.Exception;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.RemoveTaskTaskOperation;
import to.unified.unified_java_sdk.utils.Utils;

public class RemoveTaskTaskRequestBuilder {

    private RemoveTaskTaskRequest request;
    private final SDKConfiguration sdkConfiguration;

    public RemoveTaskTaskRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RemoveTaskTaskRequestBuilder request(RemoveTaskTaskRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RemoveTaskTaskResponse call() throws Exception {
        
        RequestOperation<RemoveTaskTaskRequest, RemoveTaskTaskResponse> operation
              = new RemoveTaskTaskOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
