/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.RemoveHrisDeduction2;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Utils;

public class RemoveHrisDeduction2RequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private RemoveHrisDeduction2Request request;

    public RemoveHrisDeduction2RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RemoveHrisDeduction2RequestBuilder request(@Nonnull RemoveHrisDeduction2Request request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private RemoveHrisDeduction2Request _buildRequest() {
        return this.request;
    }
    
    public RemoveHrisDeduction2RequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public RemoveHrisDeduction2Response call() {
        RequestOperation<RemoveHrisDeduction2Request, RemoveHrisDeduction2Response> operation
              = new RemoveHrisDeduction2.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
