/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.AdsCreative;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class UpdateAdsCreativeRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private AdsCreative adsCreative;

    /**
     * ID of the connection
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connection_id")
    private String connectionId;

    /**
     * Fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    private List<UpdateAdsCreativeQueryParamFields> fields;

    /**
     * ID of the Creative
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=raw")
    private String raw;

    @JsonCreator
    public UpdateAdsCreativeRequest(
            @Nonnull AdsCreative adsCreative,
            @Nonnull String connectionId,
            @Nullable List<UpdateAdsCreativeQueryParamFields> fields,
            @Nonnull String id,
            @Nullable String raw) {
        this.adsCreative = Optional.ofNullable(adsCreative)
            .orElseThrow(() -> new IllegalArgumentException("adsCreative cannot be null"));
        this.connectionId = Optional.ofNullable(connectionId)
            .orElseThrow(() -> new IllegalArgumentException("connectionId cannot be null"));
        this.fields = fields;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.raw = raw;
    }
    
    public UpdateAdsCreativeRequest(
            @Nonnull AdsCreative adsCreative,
            @Nonnull String connectionId,
            @Nonnull String id) {
        this(adsCreative, connectionId, null,
            id, null);
    }

    public AdsCreative adsCreative() {
        return this.adsCreative;
    }

    /**
     * ID of the connection
     */
    public String connectionId() {
        return this.connectionId;
    }

    /**
     * Fields to return
     */
    public Optional<List<UpdateAdsCreativeQueryParamFields>> fields() {
        return Optional.ofNullable(this.fields);
    }

    /**
     * ID of the Creative
     */
    public String id() {
        return this.id;
    }

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public Optional<String> raw() {
        return Optional.ofNullable(this.raw);
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateAdsCreativeRequest withAdsCreative(@Nonnull AdsCreative adsCreative) {
        this.adsCreative = Utils.checkNotNull(adsCreative, "adsCreative");
        return this;
    }


    /**
     * ID of the connection
     */
    public UpdateAdsCreativeRequest withConnectionId(@Nonnull String connectionId) {
        this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
        return this;
    }


    /**
     * Fields to return
     */
    public UpdateAdsCreativeRequest withFields(@Nullable List<UpdateAdsCreativeQueryParamFields> fields) {
        this.fields = fields;
        return this;
    }


    /**
     * ID of the Creative
     */
    public UpdateAdsCreativeRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public UpdateAdsCreativeRequest withRaw(@Nullable String raw) {
        this.raw = raw;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateAdsCreativeRequest other = (UpdateAdsCreativeRequest) o;
        return 
            Utils.enhancedDeepEquals(this.adsCreative, other.adsCreative) &&
            Utils.enhancedDeepEquals(this.connectionId, other.connectionId) &&
            Utils.enhancedDeepEquals(this.fields, other.fields) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.raw, other.raw);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            adsCreative, connectionId, fields,
            id, raw);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateAdsCreativeRequest.class,
                "adsCreative", adsCreative,
                "connectionId", connectionId,
                "fields", fields,
                "id", id,
                "raw", raw);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AdsCreative adsCreative;

        private String connectionId;

        private List<UpdateAdsCreativeQueryParamFields> fields;

        private String id;

        private String raw;

        private Builder() {
          // force use of static builder() method
        }

        public Builder adsCreative(@Nonnull AdsCreative adsCreative) {
            this.adsCreative = Utils.checkNotNull(adsCreative, "adsCreative");
            return this;
        }

        /**
         * ID of the connection
         */
        public Builder connectionId(@Nonnull String connectionId) {
            this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
            return this;
        }

        /**
         * Fields to return
         */
        public Builder fields(@Nullable List<UpdateAdsCreativeQueryParamFields> fields) {
            this.fields = fields;
            return this;
        }

        /**
         * ID of the Creative
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
         * 
         * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
         */
        public Builder raw(@Nullable String raw) {
            this.raw = raw;
            return this;
        }

        public UpdateAdsCreativeRequest build() {
            return new UpdateAdsCreativeRequest(
                adsCreative, connectionId, fields,
                id, raw);
        }

    }
}
