/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.TaskProject;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class UpdateTaskProjectRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private TaskProject taskProject;

    /**
     * ID of the connection
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connection_id")
    private String connectionId;

    /**
     * Fields to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=fields")
    private List<UpdateTaskProjectQueryParamFields> fields;

    /**
     * ID of the Project
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=raw")
    private String raw;

    @JsonCreator
    public UpdateTaskProjectRequest(
            @Nonnull TaskProject taskProject,
            @Nonnull String connectionId,
            @Nullable List<UpdateTaskProjectQueryParamFields> fields,
            @Nonnull String id,
            @Nullable String raw) {
        this.taskProject = Optional.ofNullable(taskProject)
            .orElseThrow(() -> new IllegalArgumentException("taskProject cannot be null"));
        this.connectionId = Optional.ofNullable(connectionId)
            .orElseThrow(() -> new IllegalArgumentException("connectionId cannot be null"));
        this.fields = fields;
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.raw = raw;
    }
    
    public UpdateTaskProjectRequest(
            @Nonnull TaskProject taskProject,
            @Nonnull String connectionId,
            @Nonnull String id) {
        this(taskProject, connectionId, null,
            id, null);
    }

    public TaskProject taskProject() {
        return this.taskProject;
    }

    /**
     * ID of the connection
     */
    public String connectionId() {
        return this.connectionId;
    }

    /**
     * Fields to return
     */
    public Optional<List<UpdateTaskProjectQueryParamFields>> fields() {
        return Optional.ofNullable(this.fields);
    }

    /**
     * ID of the Project
     */
    public String id() {
        return this.id;
    }

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public Optional<String> raw() {
        return Optional.ofNullable(this.raw);
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateTaskProjectRequest withTaskProject(@Nonnull TaskProject taskProject) {
        this.taskProject = Utils.checkNotNull(taskProject, "taskProject");
        return this;
    }


    /**
     * ID of the connection
     */
    public UpdateTaskProjectRequest withConnectionId(@Nonnull String connectionId) {
        this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
        return this;
    }


    /**
     * Fields to return
     */
    public UpdateTaskProjectRequest withFields(@Nullable List<UpdateTaskProjectQueryParamFields> fields) {
        this.fields = fields;
        return this;
    }


    /**
     * ID of the Project
     */
    public UpdateTaskProjectRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
     * 
     * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
     */
    public UpdateTaskProjectRequest withRaw(@Nullable String raw) {
        this.raw = raw;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateTaskProjectRequest other = (UpdateTaskProjectRequest) o;
        return 
            Utils.enhancedDeepEquals(this.taskProject, other.taskProject) &&
            Utils.enhancedDeepEquals(this.connectionId, other.connectionId) &&
            Utils.enhancedDeepEquals(this.fields, other.fields) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.raw, other.raw);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            taskProject, connectionId, fields,
            id, raw);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateTaskProjectRequest.class,
                "taskProject", taskProject,
                "connectionId", connectionId,
                "fields", fields,
                "id", id,
                "raw", raw);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private TaskProject taskProject;

        private String connectionId;

        private List<UpdateTaskProjectQueryParamFields> fields;

        private String id;

        private String raw;

        private Builder() {
          // force use of static builder() method
        }

        public Builder taskProject(@Nonnull TaskProject taskProject) {
            this.taskProject = Utils.checkNotNull(taskProject, "taskProject");
            return this;
        }

        /**
         * ID of the connection
         */
        public Builder connectionId(@Nonnull String connectionId) {
            this.connectionId = Utils.checkNotNull(connectionId, "connectionId");
            return this;
        }

        /**
         * Fields to return
         */
        public Builder fields(@Nullable List<UpdateTaskProjectQueryParamFields> fields) {
            this.fields = fields;
            return this;
        }

        /**
         * ID of the Project
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg.
         * 
         * <p>raw parameters: foo=bar&amp;zoo=bar -&gt; raw=foo%3Dbar%26zoo%3Dbar
         */
        public Builder raw(@Nullable String raw) {
            this.raw = raw;
            return this;
        }

        public UpdateTaskProjectRequest build() {
            return new UpdateTaskProjectRequest(
                taskProject, connectionId, fields,
                id, raw);
        }

    }
}
